---
title: "Verkefni1 - MAS201F"
author: "Isak Orn Ivarsson og Adalheidur Magnusdottir"
date: "2023-01-12"
output: html_document
---
```{r setup, include= F}
knitr::opts_chunk$set(echo=T, warning=F, message =F)
```


1. Útskýrið með ykkar eigin orðum hvers vegna það borgar sig að skipta um hurð.

Líkurnar á því að velja hurðina með bíllnum sem þú vilt eru 1 á móti 3, þú velur því eina hurð með þeim líkum. Þá eru 2/3 líkur gegn þér þar sem það eru tvær hurðar eftir. Hinsvegar opnar Monty eina hurð þar sem geit er. Þá "þjappast" mótlíkurnar frá tveim hurðum yfir í eina. Líkurnar eru því ennþá 2/3 en núna bara á einni hurð. Það er því þér í hag að skipta um hurð þar sem hurðin sem Monty valdi ekki.

2. Setjið Monty Hall gátuna stærðfræðilega fram, þar með talið að skilgreina hvert útkomumengið og hverjir eru atburðirnir sem vísað er til.

Útkomumengi:
$$
\Omega = \{Geit, Bíll\}
$$

Atburðir:
$$
Vinna = \{Bíll\}
$$
$$
Tapa = \{Geit\}
$$

Mögulegir atburðir: 
$$
\Omega = \{Vinna \cap  Tapa\}
$$

Ómögulegur atburður: 
$$
Ø = \{Vinna \cup  Tapa\}
$$



3. Teiknið skýringarmynd, eða -töflu, þar sem þið tiltakið þá atburði sem koma fyrir í þrautinni og líkurnar á þeim.

| Hurð 1        | Hurð 2          | Hurð 3        |
| :---          |    :----:       |  ---:         |
| Valin hurð    |  ÓVALIN hurð    | Óvalin hurð   |
| Líkur: 1 / 3  |  Líkur: 1/3     | Líkur: 2 / 3  |

Líkurnar eru því 1/3 þér í hag og 2/3 gegn þér. En þá opnar Monty Hall  eina hurð þar sem geit er.

| Hurð 1        | Hurð 2          | Hurð 3        |
| :---          |    :----:       |  ---:         |
| Valin hurð    | Monty Hall hurð | Óvalin hurð   |
| Líkur: 1 / 3  |  Líkur: 0       | Líkur: 2 / 3  |

Þar sem Monty Hall opnar eina hurð þar sem staðfest að ein geit er þá eru líkurnar gegn þér ennþá 2/3 nema þú veist að það er geit á bakvið hurðina sem Monty opnaði og því "þjappast mótlíkurnar" á hurðina sem stendur eftir óopin, í þessu tilviki "Hurð 3".

4. Notið tungumál stærðfræðinnar til að rökstyðja hvers vegna það borgar sig að skipta um hurð.


Bónusspurning. Nú gerist það að þáttastjórnandinn er búinn að steingleyma á bakvið hvaða hurð geitin er. Hann tekur samt sénsinn og opnar eina hurð af handahófi og sem betur fer reynist geit á bakvið hurðina. Eigið þið enn að skipta um hurð?

