---
title: "MASVerkefni2"
author: "Isak Orn, Adalheidur, Alexander & Larus"
date: "2023-01-25"
output: html_document
---

### Dæmi 1: 

  Til þess að finna út líkurnar á því að ákveðinn nemandi hefði verið eini nemandinn úr sínum hópi sem mætti getum við notað tvíkostadreifingu þar sem 1 tekur gildið að fá hóp með einum nemanda og 0 er að enginn hópur sé með einum nemanda.
  Byrjum á því að reikna út jöfnuna fyrir tvíkostadreifingu, þ.e.:
  
$$
P(X = k) = c(n, k) * p^{k} * (1-p)^{n-k}
$$
    þar sem:
      K = 1 (og 0 er þá enginn hópur sé með aðeins einum nemanda),
      n = 6 (Fjöldi í hóp) og
      p = 156/228 (Líkur) 
      
$$
P(1) = choose(6, 1)*(156/228)^1*(1-(156/228))^5 = 0.0129
$$
  
  Líkur á því að einn ákveðinn nemandi lendi í hóp þar sem hann er eini sem mætir eru um 1.3%
  Setjum þetta upp stærðfræðilega, þ.e., notum slembistærð og stika líkindadreifingarinnar:
  
$$
      X \sim Bin(n,p) > X \sim Bin(6, (156/228))
$$

    
### Dæmi 2:
  Til þess að finna út líkurnar á því að einhver nemandi hefði verið sá eini sem mætti í einhvern hóp skal reikna út tvíkostadreifingu: 
  
$$
P(X = k) = c(n, k) * p^{k} * (1-p)^{n-k}
$$
 
   þar sem:
    K = 1 (og 0 er þá enginn hópur sé með aðeins einum nemanda),
    n = 6 (fjöldi í hópi) og
    p = 156/228 (líkur)

    
$$
  P(1) = 38*choose(6, 1)*(156/228)^1*(1-(156/228))^5 = 0.4899
$$
  
  Þá eru líkurnar á því að eitthver nemandi sé sá eini sem mæti í eitthvern hóp rúmlega 50%.

  Setjum þetta upp stærðfræðilega, þ.e., notum slembistærð og stika líkindadreifingarinnar:
  
$$
      X \sim Bin(n,p) > X \sim Bin(6, (156/228) * 38 
$$

### Dæmi 3: 
  Til þess að finna mesta fjölda hópa sem hægt hefði verið að skipta nemendum upp í þannig að líkurnar á því að einn nemandi sé mættur úr einhverjum hópi séu í mesta lagi 5% er sett upp hermun
  

  
### Dæmi 4:
  Til að finna líkurnar á því að það taki meiri en 30 sekúndur að svara handahófskenndri spurningu frá hóp í liðsnámsstund þegar gert er ráð fyrir því að tíminn fylgi normaldreifingu og að það taki 40 sekúndur að meðaltali að svara einni spurningu, með staðalfrávik 10 sekúndur þá...

### Dæmi 5:
  Til að finna út úr því hve mörgmum spurningum má búast við í 80 mínútna langri kennslustund með 38 hópum af nemendum þegar gert ráð fyrir því að það er alveg slembið hvenær hópur kemur með nýja spurningu í liðsnámsstund, óháð því hve langt síðan er hópurinn bar síðast upp spurningu og hve margir hópmeðlimir eru, en hver hópur ber upp eina spurningu á 10 mínútna fresti að jafnaði, þá...

### Dæmi 6:
  Að ári væri hægt að skipta upp í hópa....

    
    


